name: pot_g
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  rxdart: ^0.28.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  slang: ^4.6.0
  slang_flutter: ^4.6.0
  flutter_svg: ^2.0.17
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  auto_route: ^10.0.1
  amplitude_flutter: ^4.3.0
  flutter_localizations:
    sdk: flutter
  dynamic_fonts: ^2.2.1
  intl: ^0.20.2
  envied: ^1.1.1
  flutter_native_splash: ^2.4.5
  firebase_core: ^3.13.0
  sheet: ^1.0.0
  nonce: ^1.2.0
  crypto: ^3.0.6
  flutter_web_auth_2: ^4.1.0
  adaptive_dialog: ^2.4.1
  collection: ^1.19.1
  device_info_plus: ^11.5.0
  mutex: ^3.1.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  bloc_concurrency: ^0.3.0
  intersperse: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  auto_route_generator: ^10.0.1
  flutter_launcher_icons: ^0.14.3
  injectable_generator: ^2.7.0
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/color.png

flutter_gen:
  integrations:
    flutter_svg: true
